# Generated by Django 5.2 on 2025-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('role', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('profile_picture', models.ImageField(upload_to='')),
                ('address', models.CharField(max_length=200)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(null=True, to='authentication.skills'),
        ),
    ]
