# Generated by Django 5.2 on 2025-05-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_company_alter_freelancer_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='authentication.skills'),
        ),
    ]
